name: Terraform

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'azure/**'
jobs:
  terraform:
    uses: foo/bar.yml@v5.8.1
    with:
      runs-on: '["arc-amd64"]'
      reduced_plan_output: true
    secrets: inherit

