name: Terraform
true:
  pull_request:
    branches:
    - master
    paths-ignore:
    - azure/**
  push:
    branches:
    - master
jobs:
  terraform:
    secrets: inherit
    uses: foo/bar.yml@v4.0
    with:
      reduced_plan_output: true
      runs-on: '["arc-amd64"]'
