name: Terraform

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'azure/**'
jobs:
  terraform:
    uses: meltwater/github-actions-terraform/.github/workflows/main.yml@v5.8.1
    with:
      runs-on: '["arc-fks-amd64"]'
      assume_role_name: GitHubActionsOIDCRole
      aws_account_id_dev: 849122192484
      aws_account_id_prod: 624839716911
      aws_account_id_root: 653197905853
      aws_account_id_setup: directory_multiple
      reduced_plan_output: true
    secrets: inherit

